title: ImagoMortis Tech Blog
description: Feinstes Hack
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  My Github: https://github.com/ImagoMortis



  # Navigation
nav:
  - title: Home
    url: /
    nav_order: 1
  - title: Dokumentation
    url: /
    nav_order: 2
    children:
      - title: Contact
        url: /Contact
        nav_order: 1
