title: ImagoMortis Tech Blog
description: Feinstes Hack
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  My Github: https://github.com/ImagoMortis


nav:
  - title: Home
    url: /index.md
    nav_order: 1
  - title: Contact
    url: /articles/Contact.md
    nav_order: 2
    parent: Home
  
 
