title: CircuitSpark
description: Feinstes Hack
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  My Github: https://github.com/ImagoMortis


nav:
  - title: Home
    url: /index
    nav_order: 1
  - title: Contact
    url: /articles/Contact
    nav_order: 2
    
  
 
